version: "3.7"
services:

  redis:
    image: redis
    container_name: cache
    expose:
      - 6379

  api:
    links:
      - redis
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_REDIS_HOST: redis

